# Generated by Django 4.1.3 on 2022-12-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0002_document_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.TextField(blank=True, null=True)),
                ('artist_name', models.TextField(blank=True, null=True)),
                ('song_url', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
